// 원본 "공정재공현황" 엑셀 컬럼 순서 그대로. key는 detail JSON 키(=원본 헤더명),
// title은 화면에 표시되는 제목이다. 공정별 컬럼(사출~출하포장)은 해당 공정 단계에
// 머물러 있는 재공수량이다.
export const PROCESS_WIP_COLS = [
  { key: "품목군", title: "품목군" },
  { key: "품목코드", title: "품목코드" },
  { key: "품목정보", title: "품목정보" },
  { key: "작업지시번호", title: "작업지시번호" },
  { key: "LOT No", title: "LOT No" },
  { key: "중간창고Location명", title: "중간창고Location명" },
  { key: "수주번호", title: "수주번호" },
  { key: "순번", title: "순번" },
  { key: "사출", title: "사출" },
  { key: "분류", title: "분류" },
  { key: "Base 인쇄", title: "Base 인쇄" },
  { key: "착색 인쇄", title: "착색 인쇄" },
  { key: "정렬", title: "정렬" },
  { key: "조립", title: "조립" },
  { key: "분리3", title: "분리3" },
  { key: "분리검사", title: "분리검사" },
  { key: "드라이검사", title: "드라이검사" },
  { key: "습윤", title: "습윤" },
  { key: "외관검사", title: "외관검사" },
  { key: "이재기", title: "이재기" },
  { key: "실링", title: "실링" },
  { key: "멸균", title: "멸균" },
  { key: "입고대기", title: "입고대기" },
  { key: "중간창고", title: "중간창고" },
  { key: "마킹", title: "마킹" },
  { key: "출하포장", title: "출하포장" },
] as const;

// 하단 합계 행에 표시할 공정별 재공수량 컬럼 — 순번은 수량이 아니라 일련번호라 제외한다.
export const PROCESS_WIP_SUM_KEYS = [
  "사출",
  "분류",
  "Base 인쇄",
  "착색 인쇄",
  "정렬",
  "조립",
  "분리3",
  "분리검사",
  "드라이검사",
  "습윤",
  "외관검사",
  "이재기",
  "실링",
  "멸균",
  "입고대기",
  "중간창고",
  "마킹",
  "출하포장",
] as const;
